// Code generated by MockGen. DO NOT EDIT.
// Source: ./clients/radom/client.go

// Package mock_radom is a generated GoMock package.
package mock_radom

import (
	reflect "reflect"

	radom "github.com/brave-intl/bat-go/libs/clients/radom"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockClient) CreateCheckoutSession(arg0 *radom.CheckoutSessionRequest) (*radom.CheckoutSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", arg0)
	ret0, _ := ret[0].(*radom.CheckoutSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockClientMockRecorder) CreateCheckoutSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockClient)(nil).CreateCheckoutSession), arg0)
}
