// Code generated by MockGen. DO NOT EDIT.
// Source: ./eyeshade/datastore.go

// Package eyeshade is a generated GoMock package.
package eyeshade

import (
	context "context"
	countries "github.com/brave-intl/bat-go/eyeshade/countries"
	models "github.com/brave-intl/bat-go/eyeshade/models"
	inputs "github.com/brave-intl/bat-go/utils/inputs"
	v4 "github.com/golang-migrate/migrate/v4"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
	reflect "reflect"
)

// MockDatastore is a mock of Datastore interface
type MockDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockDatastoreMockRecorder
}

// MockDatastoreMockRecorder is the mock recorder for MockDatastore
type MockDatastoreMockRecorder struct {
	mock *MockDatastore
}

// NewMockDatastore creates a new mock instance
func NewMockDatastore(ctrl *gomock.Controller) *MockDatastore {
	mock := &MockDatastore{ctrl: ctrl}
	mock.recorder = &MockDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatastore) EXPECT() *MockDatastoreMockRecorder {
	return m.recorder
}

// RawDB mocks base method
func (m *MockDatastore) RawDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// RawDB indicates an expected call of RawDB
func (mr *MockDatastoreMockRecorder) RawDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawDB", reflect.TypeOf((*MockDatastore)(nil).RawDB))
}

// NewMigrate mocks base method
func (m *MockDatastore) NewMigrate() (*v4.Migrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMigrate")
	ret0, _ := ret[0].(*v4.Migrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMigrate indicates an expected call of NewMigrate
func (mr *MockDatastoreMockRecorder) NewMigrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMigrate", reflect.TypeOf((*MockDatastore)(nil).NewMigrate))
}

// Migrate mocks base method
func (m *MockDatastore) Migrate(arg0 ...uint) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Migrate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate
func (mr *MockDatastoreMockRecorder) Migrate(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockDatastore)(nil).Migrate), arg0...)
}

// RollbackTxAndHandle mocks base method
func (m *MockDatastore) RollbackTxAndHandle(tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTxAndHandle", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTxAndHandle indicates an expected call of RollbackTxAndHandle
func (mr *MockDatastoreMockRecorder) RollbackTxAndHandle(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTxAndHandle", reflect.TypeOf((*MockDatastore)(nil).RollbackTxAndHandle), tx)
}

// RollbackTx mocks base method
func (m *MockDatastore) RollbackTx(tx *sqlx.Tx) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RollbackTx", tx)
}

// RollbackTx indicates an expected call of RollbackTx
func (mr *MockDatastoreMockRecorder) RollbackTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockDatastore)(nil).RollbackTx), tx)
}

// ResolveConnection mocks base method
func (m *MockDatastore) ResolveConnection(ctx context.Context) (context.Context, *sqlx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveConnection", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*sqlx.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveConnection indicates an expected call of ResolveConnection
func (mr *MockDatastoreMockRecorder) ResolveConnection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConnection", reflect.TypeOf((*MockDatastore)(nil).ResolveConnection), ctx)
}

// WithTx mocks base method
func (m *MockDatastore) WithTx(ctx context.Context) (context.Context, *sqlx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*sqlx.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WithTx indicates an expected call of WithTx
func (mr *MockDatastoreMockRecorder) WithTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockDatastore)(nil).WithTx), ctx)
}

// Rollback mocks base method
func (m *MockDatastore) Rollback(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Rollback", ctx)
}

// Rollback indicates an expected call of Rollback
func (mr *MockDatastoreMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDatastore)(nil).Rollback), ctx)
}

// Commit mocks base method
func (m *MockDatastore) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit
func (mr *MockDatastoreMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDatastore)(nil).Commit), ctx)
}

// GetAccountEarnings mocks base method
func (m *MockDatastore) GetAccountEarnings(ctx context.Context, options models.AccountEarningsOptions) (*[]models.AccountEarnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountEarnings", ctx, options)
	ret0, _ := ret[0].(*[]models.AccountEarnings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountEarnings indicates an expected call of GetAccountEarnings
func (mr *MockDatastoreMockRecorder) GetAccountEarnings(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountEarnings", reflect.TypeOf((*MockDatastore)(nil).GetAccountEarnings), ctx, options)
}

// GetAccountSettlementEarnings mocks base method
func (m *MockDatastore) GetAccountSettlementEarnings(ctx context.Context, options models.AccountSettlementEarningsOptions) (*[]models.AccountSettlementEarnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSettlementEarnings", ctx, options)
	ret0, _ := ret[0].(*[]models.AccountSettlementEarnings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSettlementEarnings indicates an expected call of GetAccountSettlementEarnings
func (mr *MockDatastoreMockRecorder) GetAccountSettlementEarnings(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSettlementEarnings", reflect.TypeOf((*MockDatastore)(nil).GetAccountSettlementEarnings), ctx, options)
}

// GetBalances mocks base method
func (m *MockDatastore) GetBalances(ctx context.Context, accountIDs []string) (*[]models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalances", ctx, accountIDs)
	ret0, _ := ret[0].(*[]models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalances indicates an expected call of GetBalances
func (mr *MockDatastoreMockRecorder) GetBalances(ctx, accountIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalances", reflect.TypeOf((*MockDatastore)(nil).GetBalances), ctx, accountIDs)
}

// GetPending mocks base method
func (m *MockDatastore) GetPending(ctx context.Context, accountIDs []string) (*[]models.PendingTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", ctx, accountIDs)
	ret0, _ := ret[0].(*[]models.PendingTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending
func (mr *MockDatastoreMockRecorder) GetPending(ctx, accountIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockDatastore)(nil).GetPending), ctx, accountIDs)
}

// GetTransactions mocks base method
func (m *MockDatastore) GetTransactions(ctx context.Context, constraints ...map[string]string) (*[]models.Transaction, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range constraints {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactions", varargs...)
	ret0, _ := ret[0].(*[]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions
func (mr *MockDatastoreMockRecorder) GetTransactions(ctx interface{}, constraints ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, constraints...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockDatastore)(nil).GetTransactions), varargs...)
}

// GetTransactionsByAccount mocks base method
func (m *MockDatastore) GetTransactionsByAccount(ctx context.Context, accountID string, txTypes []string) (*[]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByAccount", ctx, accountID, txTypes)
	ret0, _ := ret[0].(*[]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByAccount indicates an expected call of GetTransactionsByAccount
func (mr *MockDatastoreMockRecorder) GetTransactionsByAccount(ctx, accountID, txTypes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByAccount", reflect.TypeOf((*MockDatastore)(nil).GetTransactionsByAccount), ctx, accountID, txTypes)
}

// InsertConvertableTransactions mocks base method
func (m *MockDatastore) InsertConvertableTransactions(ctx context.Context, txs []models.ConvertableTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertConvertableTransactions", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertConvertableTransactions indicates an expected call of InsertConvertableTransactions
func (mr *MockDatastoreMockRecorder) InsertConvertableTransactions(ctx, txs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertConvertableTransactions", reflect.TypeOf((*MockDatastore)(nil).InsertConvertableTransactions), ctx, txs)
}

// InsertTransactions mocks base method
func (m *MockDatastore) InsertTransactions(ctx context.Context, txs *[]models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactions", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransactions indicates an expected call of InsertTransactions
func (mr *MockDatastoreMockRecorder) InsertTransactions(ctx, txs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactions", reflect.TypeOf((*MockDatastore)(nil).InsertTransactions), ctx, txs)
}

// GetActiveCountryGroups mocks base method
func (m *MockDatastore) GetActiveCountryGroups(ctx context.Context) (*[]countries.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCountryGroups", ctx)
	ret0, _ := ret[0].(*[]countries.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCountryGroups indicates an expected call of GetActiveCountryGroups
func (mr *MockDatastoreMockRecorder) GetActiveCountryGroups(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCountryGroups", reflect.TypeOf((*MockDatastore)(nil).GetActiveCountryGroups), ctx)
}

// GetReferralGroups mocks base method
func (m *MockDatastore) GetReferralGroups(ctx context.Context, activeAt inputs.Time) (*[]countries.ReferralGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralGroups", ctx, activeAt)
	ret0, _ := ret[0].(*[]countries.ReferralGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralGroups indicates an expected call of GetReferralGroups
func (mr *MockDatastoreMockRecorder) GetReferralGroups(ctx, activeAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralGroups", reflect.TypeOf((*MockDatastore)(nil).GetReferralGroups), ctx, activeAt)
}

// GetSettlementStats mocks base method
func (m *MockDatastore) GetSettlementStats(ctx context.Context, options models.SettlementStatOptions) (*models.SettlementStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettlementStats", ctx, options)
	ret0, _ := ret[0].(*models.SettlementStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettlementStats indicates an expected call of GetSettlementStats
func (mr *MockDatastoreMockRecorder) GetSettlementStats(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettlementStats", reflect.TypeOf((*MockDatastore)(nil).GetSettlementStats), ctx, options)
}

// GetGrantStats mocks base method
func (m *MockDatastore) GetGrantStats(ctx context.Context, options models.GrantStatOptions) (*models.GrantStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantStats", ctx, options)
	ret0, _ := ret[0].(*models.GrantStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrantStats indicates an expected call of GetGrantStats
func (mr *MockDatastoreMockRecorder) GetGrantStats(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantStats", reflect.TypeOf((*MockDatastore)(nil).GetGrantStats), ctx, options)
}
