version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - revive
    - unused
  settings:
    cyclop:
      max-complexity: 10
      package-average: 10
    errcheck:
      check-type-assertions: true
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    revive:
      rules:
        - name: if-return
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
