version: "3.4"

networks:
  grant:
    driver: bridge

services:
  web:
    environment:
      - "REPUTATION_SERVER=http://reputation-web-grant:3334"
      - "REPUTATION_TOKEN=foobarfoobar"
    depends_on:
      - reputation-web-grant
  reputation-postgres-grant:
    container_name: reputation-postgres-grant
    image: postgres:14
    environment:
      - "POSTGRES_USER=reputation"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=reputation"
    networks:
      - grant
    ports:
      - "3402:5432"
  reputation-web-grant:
    container_name: reputation-web-grant
    image: reputation-web
    # restart: always
    ports:
      - 3334:3334
    environment:
      - "ENV=production"
      - "ALLOW_DEBUG_APK=1"
      - "API_APPLE_KEY_ID=1"
      - "API_APPLE_BASE_URL=https://api.development.devicecheck.apple.com"
      - "API_APPLE_PRIVATE_KEY=1"
      - "API_APPLE_TEAM_ID=1"
      - "DATABASE_URL=postgres://reputation:password@reputation-postgres-grant:5432/reputation?sslmode=disable"
      - "DATABASE_MIGRATIONS_URL=file:///migrations"
      - "GRPC_ENABLED=1"
      - "IOS_ENROLLMENT_WAIT_HOURS=720h"
      - "TOKEN_LIST=636765a9-1f92-4b40-ab0b-85ebd1e2c23d"
      - "TEST_TAGS=integration"
      - "GOTEST=go test"
    depends_on:
      - reputation-postgres-grant
    networks:
      - grant
