DROP INDEX wallets_deposit_account_provider_id;
DROP INDEX wallets_deposit_account_anonymous_address;

ALTER TABLE wallets DROP COLUMN user_deposit_account_anonymous_address;
ALTER TABLE wallets DROP COLUMN user_deposit_account_provider;
ALTER TABLE wallets DROP COLUMN user_deposit_account_provider_id;
