version: "3.4"

services:
  redis-master:
    container_name: redis-master
    image: bitnami/redis-cluster:6.2.6
    environment:
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=1
      - REDIS_ACLFILE=/etc/redis/users.acl
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-master redis-slave-3 redis-slave-1 redis-slave-2'
      - REDIS_PORT=0
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
    ports:
      - "6380:6379"
    volumes:
      - ./test/redis/tls:/etc/redis
    depends_on:
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3

  redis-slave-1:
    container_name: redis-slave-1
    image: bitnami/redis-cluster:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_ACLFILE=/etc/redis/users.acl
      - 'REDIS_NODES=redis-master redis-slave-3 redis-slave-1 redis-slave-2'
      - REDIS_PORT=0
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
    ports:
      - "6381:6379"
    volumes:
      - ./test/redis/tls:/etc/redis

  redis-slave-2:
    container_name: redis-slave-2
    image: bitnami/redis-cluster:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_ACLFILE=/etc/redis/users.acl
      - 'REDIS_NODES=redis-master redis-slave-3 redis-slave-1 redis-slave-2'
      - REDIS_PORT=0
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
    ports:
      - "6382:6379"
    volumes:
      - ./test/redis/tls:/etc/redis

  redis-slave-3:
    container_name: redis-slave-3
    image: bitnami/redis-cluster:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_ACLFILE=/etc/redis/users.acl
      - 'REDIS_NODES=redis-master redis-slave-3 redis-slave-1 redis-slave-2'
      - REDIS_PORT=0
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
      - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
      - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
    ports:
      - "6383:6379"
    volumes:
      - ./test/redis/tls:/etc/redis
