// Code generated by MockGen. DO NOT EDIT.
// Source: utils/clients/balance/client.go

// Package mock_balance is a generated GoMock package.
package mock_balance

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	go_uuid "github.com/satori/go.uuid"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// InvalidateBalance mocks base method
func (m *MockClient) InvalidateBalance(ctx context.Context, id go_uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateBalance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateBalance indicates an expected call of InvalidateBalance
func (mr *MockClientMockRecorder) InvalidateBalance(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateBalance", reflect.TypeOf((*MockClient)(nil).InvalidateBalance), ctx, id)
}
