tokens:
  - id: "brave search captcha sku token v1 - productoin"
    version: 2
    location: "search.brave.com"
    first_party_caveats:
      - sku: "brave-search-captcha"
      - price: 0
      - currency: "BAT"
      - description: "single use captcha sku"
      - credential_type: "single-use"
