AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  email-webhook
  
  Sample SAM Template for email-webhook

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  EmailWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: webhook/
      Handler: webhook
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST

  EmailUnsubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: unsubscribe/
      Handler: unsubscribe
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /unsubscribe
            Method: GET

Outputs:
  EmailWebhookAPI:
    Description: "API Gateway endpoint URL for Prod environment email webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  EmailWebhookFunction:
    Description: "Email Webhook Function ARN"
    Value: !GetAtt EmailWebhookFunction.Arn
  EmailWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt EmailWebhookFunctionRole.Arn

  EmailUnsubscribeAPI:
    Description: "API Gateway endpoint URL for Prod environment for unsubscribe"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/unsubscribe/"
  EmailUnsubscribeFunction:
    Description: "unsubscribe lambda ARN"
    Value: !GetAtt EmailUnsubscribeFunction.Arn
  EmailUnsubscribeFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt EmailUnsubscribeFunctionRole.Arn
