version: "3.4"

networks:
  rewards:
    driver: bridge

services:
  # dev-refresh service will start up a rewards server bound to host port 3343
  # which allows one to do `docker restart rewards-dev-refresh` when the user
  # wants to "restart" the service running new code.  This is especially helpful
  # when you hook it up to `fswatch` type utilities, causing a re-run of `go run`
  # every time a file changes.
  rewards-dev-refresh:
    container_name: rewards-dev-refresh
    image: golang:1.13.4
    ports:
      - "3343:3343"
      - "6061:6061"
    command: "go run main.go serve rewards rest"
    volumes:
      - ../:/src
    working_dir: /src
    networks:
      - rewards
    environment:
      - PPROF_ENABLED
      - ENV=local
      - ADDR=:3343
      - RATIOS_SERVICE=https://bat-ratios-dev.herokuapp.com/
      - RATIOS_TOKEN
      - DEFAULT_TIP_CHOICES=5,10,20
      - DEFAULT_MONTHLY_CHOICES=5,10,20
      - DEFAULT_CURRENCY=USD
      - RATIOS_CACHE_EXPIRY=1m
      - RATIOS_CACHE_PURGE=2m
