// Code generated by MockGen. DO NOT EDIT.
// Source: ./clients/stripe/client.go

// Package mock_stripe is a generated GoMock package.
package mock_stripe

import (
	context "context"
	reflect "reflect"

	stripe "github.com/brave-intl/bat-go/libs/clients/stripe"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateOnrampSession mocks base method.
func (m *MockClient) CreateOnrampSession(ctx context.Context, integrationMode, walletAddress, sourceCurrency, sourceExchangeAmount, destinationNetwork, destinationCurrency string, supportedDestinationNetworks []string) (*stripe.OnrampSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnrampSession", ctx, integrationMode, walletAddress, sourceCurrency, sourceExchangeAmount, destinationNetwork, destinationCurrency, supportedDestinationNetworks)
	ret0, _ := ret[0].(*stripe.OnrampSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOnrampSession indicates an expected call of CreateOnrampSession.
func (mr *MockClientMockRecorder) CreateOnrampSession(ctx, integrationMode, walletAddress, sourceCurrency, sourceExchangeAmount, destinationNetwork, destinationCurrency, supportedDestinationNetworks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnrampSession", reflect.TypeOf((*MockClient)(nil).CreateOnrampSession), ctx, integrationMode, walletAddress, sourceCurrency, sourceExchangeAmount, destinationNetwork, destinationCurrency, supportedDestinationNetworks)
}
