// Code generated by MockGen. DO NOT EDIT.
// Source: ./promotion/drain.go

// Package promotion is a generated GoMock package.
package promotion

import (
	context "context"
	cbr "github.com/brave-intl/bat-go/utils/clients/cbr"
	wallet "github.com/brave-intl/bat-go/utils/wallet"
	gomock "github.com/golang/mock/gomock"
	go_uuid "github.com/satori/go.uuid"
	decimal "github.com/shopspring/decimal"
	reflect "reflect"
)

// MockDrainWorker is a mock of DrainWorker interface
type MockDrainWorker struct {
	ctrl     *gomock.Controller
	recorder *MockDrainWorkerMockRecorder
}

// MockDrainWorkerMockRecorder is the mock recorder for MockDrainWorker
type MockDrainWorkerMockRecorder struct {
	mock *MockDrainWorker
}

// NewMockDrainWorker creates a new mock instance
func NewMockDrainWorker(ctrl *gomock.Controller) *MockDrainWorker {
	mock := &MockDrainWorker{ctrl: ctrl}
	mock.recorder = &MockDrainWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDrainWorker) EXPECT() *MockDrainWorkerMockRecorder {
	return m.recorder
}

// RedeemAndTransferFunds mocks base method
func (m *MockDrainWorker) RedeemAndTransferFunds(ctx context.Context, credentials []cbr.CredentialRedemption, walletID go_uuid.UUID, total decimal.Decimal) (*wallet.TransactionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemAndTransferFunds", ctx, credentials, walletID, total)
	ret0, _ := ret[0].(*wallet.TransactionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedeemAndTransferFunds indicates an expected call of RedeemAndTransferFunds
func (mr *MockDrainWorkerMockRecorder) RedeemAndTransferFunds(ctx, credentials, walletID, total interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemAndTransferFunds", reflect.TypeOf((*MockDrainWorker)(nil).RedeemAndTransferFunds), ctx, credentials, walletID, total)
}
