name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - prod
      - dev
  pull_request:
    branches:
      - master
      - prod
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [libs, services, tools, cmd, main]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          working-directory: ${{ matrix.work-dir }}
          version: v2.11.4
          args: --timeout 3m

  # GHA doesn't implement aggregated matrix status checks natively: https://github.com/orgs/community/discussions/26822
  lint:
    name: lint
    runs-on: ubuntu-slim
    needs: [golangci]
    steps:
      - run: exit 0
