name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Setup SAM environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v1

# FIXME: need to get the appropriate credentials
#     - name: Configure AWS Credentials 
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         role-to-assume: 
#         role-session-name: 
#         aws-region: us-west-2

      - name: Build lambdas inside Docker containers
        run: sam build --use-container

# FIXME: when credentials are set, we can deploy
# fix the stack name and the s3 bucket
#     - name: Deploy email lambdas
#       run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name usage-ping-etl-stack --s3-bucket lambda-usage-pings-formatter-artifacts-stg
