name: Deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Setup SAM environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        env:
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::021268868874:role/bravex-lambdas-sbx-github-actions20220920082446554100000003
          role-session-name: bravex-sbx-github-actions
          aws-region: us-west-2

      - name: Build lambdas inside Docker containers
        run: sam build --use-container --build-dir ./serverless/email/build --base-dir ./serverless/email/ --template-file ./serverless/email/template.yaml --debug

      - name: Deploy email lambdas
        env:
          DEPLOY_ENV: sbx
          APIGATEWAY_TRACING: Active
          EVENT_LAMBDA_TRACING: Active
          UNSUBSCRIBE_LAMBDA_TRACING: Active
          WEBHOOK_LAMBDA_TRACING: Active
          LAMBDA_ARTIFACTS_BUCKET: bravex-lambda-artifacts-sbx-20220920082445588400000002
        run: sam deploy --no-confirm-changeset --parameter-overrides 'ParameterKey=DeploymentEnvironment,ParameterValue=$DEPLOY_ENV ParameterKey=WebhookLambdaTracing,ParameterValue=$WEBHOOK_LAMBDA_TRACING ParameterKey=APIGatewayTracing,ParameterValue=$APIGATEWAY_TRACING ParameterKey=EventLambdaTracing,ParameterValue=$EVENT_LAMBDA_TRACING ParameterKey=UnsubscribeLambdaTracing,ParameterValue=$UNSUBSCRIBE_LAMBDA_TRACING' --template-file ./serverless/email/build/template.yaml --no-fail-on-empty-changeset --stack-name bravex-frontend --s3-bucket $LAMBDA_ARTIFACTS_BUCKET --debug
